//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materijal_na_Skladište
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materijal_na_Skladište()
        {
            this.Stavka_primke = new HashSet<Stavka_primke>();
            this.Stavka_rezanja = new HashSet<Stavka_rezanja>();
        }
    
        public int Materijal_ID { get; set; }
        public int Skladiste_ID { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Materijal Materijal { get; set; }
        public virtual Skladište Skladište { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_primke> Stavka_primke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_rezanja> Stavka_rezanja { get; set; }
    }
}
