//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ostatak()
        {
            this.Stavka_rezanja = new HashSet<Stavka_rezanja>();
        }
    
        public int ID_Ostatak { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<decimal> Duzina_ostatka { get; set; }
        public Nullable<int> Plan_Rezanja_ID { get; set; }
        public Nullable<int> Materijal_ID { get; set; }
    
        public virtual Materijal Materijal { get; set; }
        public virtual Plan_rezanja Plan_rezanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_rezanja> Stavka_rezanja { get; set; }
    }
}
