//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_primke
    {
        public int ID_Stavka { get; set; }
        public int Kolicina { get; set; }
        public Nullable<int> Materijal_ID { get; set; }
        public Nullable<int> Primka_ID { get; set; }
        public Nullable<int> Skladiste_ID { get; set; }
    
        public virtual Materijal Materijal { get; set; }
        public virtual Materijal_na_Skladište Materijal_na_Skladište { get; set; }
        public virtual Skladišna_primka Skladišna_primka { get; set; }
    }
}
